INSERT INTO finalproject.warehouse(warehouse_id,name,location) values (1,'wh_sp', 'SP')
INSERT INTO finalproject.warehouse(warehouse_id,name,location) values (2,'wh_ma', 'MA')
INSERT INTO finalproject.section(id,name) values (1,'congelados')
INSERT INTO finalproject.section(id,name) values (2,'eletronicos')
INSERT INTO finalproject.warehouse_section(warehouse_warehouse_id,section_id) values (1,1)
INSERT INTO finalproject.warehouse_section(warehouse_warehouse_id,section_id) values (1,2)
INSERT INTO finalproject.warehouse_section(warehouse_warehouse_id,section_id) values (2,1)
INSERT INTO finalproject.product(id,name) values (1,'macarrao')
INSERT INTO finalproject.product(id,name) values (2,'bacon')
INSERT INTO finalproject.product(id,name) values (3,'uva')